import type { CatalogConfig } from '../domain/CatalogConfig'
import type { Product } from '../domain/Product'

const description = 'Calçado confortável e versátil para acompanhar a rotina com estilo.'

export const mockProducts: Product[] = [
  {
    sku: 'SAP000001',
    group: 'air-max-90',
    slug: 'nike-air-max-90-branco-42',
    name: 'Air Max 90',
    brand: 'Nike',
    category: 'Tênis',
    gender: 'Masculino',
    color: 'Branco',
    size: '42',
    price: 299.9,
    description,
    images: ['SAP000001-1'],
    available: true,
    featured: true,
    newArrival: false,
    order: 1,
  },
  {
    sku: 'SAP000002',
    group: 'air-max-90',
    slug: 'nike-air-max-90-branco-41',
    name: 'Air Max 90',
    brand: 'Nike',
    category: 'Tênis',
    gender: 'Masculino',
    color: 'Branco',
    size: '41',
    price: 299.9,
    promotionalPrice: 279.9,
    description,
    images: ['SAP000001-1'],
    available: true,
    featured: true,
    newArrival: true,
    order: 2,
  },
  {
    sku: 'SAP000003',
    group: 'forum-low',
    slug: 'adidas-forum-low-preto-40',
    name: 'Forum Low',
    brand: 'Adidas',
    category: 'Tênis',
    gender: 'Unissex',
    color: 'Preto',
    size: '40',
    price: 249.9,
    description,
    images: ['SAP000001-1'],
    available: true,
    featured: false,
    newArrival: true,
    order: 3,
  },
  {
    sku: 'SAP000004',
    group: 'sapato-social',
    slug: 'ferracini-sapato-social-marrom-41',
    name: 'Sapato Social',
    brand: 'Ferracini',
    category: 'Social',
    gender: 'Masculino',
    color: 'Marrom',
    size: '41',
    price: 189.9,
    description,
    images: ['SAP000001-1'],
    available: false,
    featured: false,
    newArrival: false,
    order: 4,
  },
  {
    sku: 'SAP000005',
    group: 'bota-feminina',
    slug: 'vizzano-bota-feminina-preto-38',
    name: 'Bota Feminina',
    brand: 'Vizzano',
    category: 'Bota',
    gender: 'Feminino',
    color: 'Preto',
    size: '38',
    price: 219.9,
    promotionalPrice: 199.9,
    description,
    images: ['SAP000001-1'],
    available: true,
    featured: true,
    newArrival: true,
    order: 5,
  },
]

export const mockConfig: CatalogConfig = {
  storeName: 'Passo Certo',
  whatsapp: '5511999990000',
  instagram: '@passocerto_mock',
  homeTitle: 'Encontre o par que combina com você',
  homeSubtitle: 'Explore nossa seleção de calçados e fale diretamente com a gente.',
  whatsappText: 'Olá! Vi o catálogo e gostaria de mais informações.',
  showPrice: true,
  showUnavailable: true,
  pageSize: 4,
}
